service: video-generator

frameworkVersion: '3'

plugins:
  - serverless-python-requirements
  - serverless-lift

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    DB_HOST: ${ssm:/shiroad/api/${self:custom.stage}/DATABASE_HOST}
    DB_NAME: ${ssm:/shiroad/api/${self:custom.stage}/DATABASE_NAME}
    DB_USER: ${ssm:/shiroad/api/${self:custom.stage}/DATABASE_USER}
    DB_PASSWORD: ${ssm:/shiroad/api/${self:custom.stage}/DATABASE_PASSWORD}
    S3_BUCKET_NAME: ${ssm:/shiroad/api/${self:custom.stage}/AWS_S3_BUCKET_ASSETS}

custom:
  stage: ${opt:stage, 'dev'}
  pythonRequirements:
    dockerizePip: false
    zip: true
    slim: true
    stripPackages: false
    useDownloadCache: true
    useStaticCache: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - s3transfer
      - setuptools
      - six

constructs:
  shiroad-video:
    type: queue
    worker:
      name: shiroad-video-${self:custom.stage}
      handler: src/main.lambda_handler
      timeout: 900
#      reservedConcurrency: 20
      memorySize: 2056
      layers:
        - arn:aws:lambda:us-east-1:767397968725:layer:python-ffmpeg:3
    batchSize: 10
    maxBatchingWindow: 2
    extensions:
      queue:
        Properties:
          QueueName: shiroad-video-${self:custom.stage}

package:
  individually: true
  exclude:
    - node_modules/**
    - cache/**
    - test/**
    - .git/**
    - .github/**
